apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: andreas-kavountzis-live-pfs
commonAnnotations:
  enzo: "true"
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
patches:
  - path: host_patch.json
    target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: react-intro
